repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        files: \.(json|ya?ml|toml|env(\.[^/]+)?|ini|cfg|py)$
        exclude: |
          (^tests?/fixtures?/)|(^docs?/)|(\.svg$)|(\.lock$)|(\.min\.(js|css)$)|
          (^node_modules/)|(^venv/)|(^\.venv/)|(^dist/)|(^build/)|(^\.git/)
        args:
          - --baseline
          - .secrets.baseline
          - --exclude-lines
          - '-----BEGIN PUBLIC KEY-----'


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-yaml

      - id: check-added-large-files
        args: ["--maxkb=512"]

      - id: trailing-whitespace
      - id: end-of-file-fixer
